### ISSUE TITLE
frontend 安装编译报错

### ISSUE THREAD

**Issue by sunyongtao87** [myide/see#1]
文档上没有frontend的安装操作步骤，在frontend目录下执行npm  install  然后在执行npm run  build报错

**Comment by chenkun1998** [comment]
加群讨论吧，qq群号 630791951




| |
chenkun
邮箱：chenkun1998@163.com
|

Signature is customized by Netease Mail Master

在2018年09月10日 23:51，sunyongtao87 写道：

文档上没有frontend的安装操作步骤，在frontend目录下执行npm install 然后在执行npm run build报错

**Comment by guomaoqiu** [comment]
![image](https://user-images.githubusercontent.com/9714859/48889889-38b70100-ee72-11e8-8bdd-0e9dde43f0d9.png)
大大 您的安装文档中没得5.3 哇~~~

**Comment by myide** [comment]
安装文档调整了，前端打包在6.6呢
