### ISSUE TITLE
选择数据库为空

### ISSUE THREAD

**Issue by Yukino0319** [myide/see#19]
![1](https://user-images.githubusercontent.com/16753038/56625258-13bbf980-666f-11e9-9b47-3c8105913f2d.png)

选择数据库时没有响应。后台应该怎么查日志？

按照安装文档安装的，每一步都成功了。

**Comment by myide** [comment]
这是没有显示数据库。
你需要先添加数据库，再设置用户权限那里选择它，再设置订阅数据库。
订阅后就能看到数据库了。
