### ISSUE TITLE
工单点击执行，inception日志显示执行了2次update

### ISSUE THREAD

**Issue by FifthMan** [myide/see#23]
![image](https://user-images.githubusercontent.com/31461026/61358989-12851c00-a8ae-11e9-916d-49720b333f25.png)

![image](https://user-images.githubusercontent.com/31461026/61359062-3b0d1600-a8ae-11e9-9142-4f482804136f.png)

如图所示

**Comment by myide** [comment]
你看看第一个截图里，不是执行了2次，是1次 check 1次execute

**Comment by FifthMan** [comment]
好的，谢谢
