### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by liliang8858** [myide/see#3]
http://xxx.xxx.xx.xx/api/dashboard/chart/

500 Internal Server Error

**Comment by myide** [comment]
运行项目前，需要先创建inception数据库，步骤见文档的此处：
![image](https://user-images.githubusercontent.com/8575341/45862990-b5f8c380-bda6-11e8-802d-82db4ac542bf.png)

**Comment by liliang8858** [comment]
@myide 创建过了

**Comment by liliang8858** [comment]
@myide  我点击锁屏后，怎么解屏

**Comment by liliang8858** [comment]
@myide 现在一片空白

**Comment by liliang8858** [comment]
![image](https://user-images.githubusercontent.com/38367404/45863081-2bfd2a80-bda7-11e8-84b1-4960db83b108.png)

**Comment by myide** [comment]
这个console log是锁屏问题引起的，清除浏览器缓存就可以显示了，下个版本会解决

**Comment by liliang8858** [comment]
好的

**Comment by myide** [comment]
inception库你没创建，这个问题 你在群里看

**Comment by liliang8858** [comment]
这是哪个库   sqlweb  这个库建了

**Comment by myide** [comment]
二楼我回答你了呀
