### ISSUE TITLE
执行工单报错  500 Internal server error

### ISSUE THREAD

**Issue by BiDaodao** [myide/see#8]
工单处理 -> 执行工单时 报错 ，如下图

![image](https://user-images.githubusercontent.com/33045796/53694541-54c02c00-3deb-11e9-93eb-cb373ffce5b4.png)

**Comment by myide** [comment]
看日志

**Comment by myide** [comment]
redis没开启也是500

**Comment by BiDaodao** [comment]
把Redis启动了确实不报500 ，这个又是什么鬼？

![image](https://user-images.githubusercontent.com/33045796/53704725-39403a00-3e5a-11e9-84a2-eb7b8114a284.png)

还有我好像没找到工单详情... awkward
